import { InfinityIcon, Database, BarChart3, Headphones, Sparkles, ServerCog, Boxes, GitBranch, TestTube, Zap, Globe, Shield, Users } from "lucide-react";

export const plans = {
    monthly: {
      name: "Professional",
      price: 29,
      description: "Ideal for growing businesses and teams",
      icon: <Zap className="w-6 h-6" />,
      features: [
        "Unlimited projects",
        "100GB storage",
        "Advanced analytics",
        "Priority support",
        "AI Auto restructure",
        "AI API Creation",
        "AI Schema Creations",
        "AI Data Pipelines",
        "AI Tests"
      ],
      popular: true,
      color: "border-indigo-500"
    },
    yearly: {
      name: "Professional",
      price: 290,
      originalPrice: 348,
      description: "Ideal for growing businesses and teams",
      icon: <Zap className="w-6 h-6" />,
      features: [
        "Unlimited projects",
        "100GB storage",
        "Advanced analytics",
        "Priority support",
        "AI Auto restructure",
        "AI API Creation",
        "AI Schema Creations",
        "AI Data Pipelines",
        "AI Tests"
      ],
      popular: true,
      color: "border-indigo-500"
    }
  };


    export const additionalFeatures = [
    { icon: <Globe className="w-5 h-5" />, title: "Global CDN", description: "Lightning-fast content delivery worldwide" },
    { icon: <Shield className="w-5 h-5" />, title: "Enterprise Security", description: "Bank-level encryption and compliance" },
    { icon: <Users className="w-5 h-5" />, title: "Team Collaboration", description: "Real-time collaboration tools" },
    { icon: <Headphones className="w-5 h-5" />, title: "24/7 Support", description: "Round-the-clock expert assistance" }
  ];

  export const stats = [
    { value: "99.9%", label: "Uptime SLA" },
    { value: "< 100ms", label: "Response Time" },
    { value: "150+", label: "Integrations" },
    { value: "50K+", label: "Happy Customers" }
  ];
export const FEATURES = [
  {
    title: 'Unlimited Projects',
    description: 'Create, organize, and ship without limits. Spin up sandboxes or production apps on demand.',
    icon: InfinityIcon,
  },
  {
    title: '100GB Storage',
    description: 'Fast, encrypted storage with automatic tiering and instant snapshots.',
    icon: Database,
  },
  {
    title: 'Advanced Analytics',
    description: 'Real-time dashboards, cohort analysis, and anomaly detection out of the box.',
    icon: BarChart3,
  },
  {
    title: 'Priority Support',
    description: 'Direct access to senior engineers with <60s median response in critical windows.',
    icon: Headphones,
  },
  {
    title: 'AI Auto Restructure',
    description: 'Automatic schema refactors and index proposals to keep performance razor-sharp.',
    icon: Sparkles,
  },
  {
    title: 'AI API Creation',
    description: 'Generate secure, typed REST and GraphQL endpoints from your data models.',
    icon: ServerCog,
  },
  {
    title: 'AI Schema Creations',
    description: 'Describe your entities in plain English—get normalized, versioned schemas instantly.',
    icon: Boxes,
  },
  {
    title: 'AI Data Pipelines',
    description: 'Declarative ETL with error recovery, retries, and lineage tracking.',
    icon: GitBranch,
  },
  {
    title: 'AI Tests',
    description: 'Autogenerated unit and integration tests for queries, mutations, and jobs.',
    icon: TestTube,
  },
];