'use client';

import { useEffect, useRef } from 'react';
import {
  Infinity,
  Database,
  BarChart3,
  Headphones,
  Sparkles,
  ServerCog,
  Boxes,
  GitBranch,
  TestTube,
  ArrowRight,
} from 'lucide-react';
import FeatureCard from './_components/FeatureCard';

const FEATURES = [
  {
    title: 'Unlimited Projects',
    description: 'Create, organize, and ship without limits. Spin up sandboxes or production apps on demand.',
    icon: Infinity,
  },
  {
    title: '100GB Storage',
    description: 'Fast, encrypted storage with automatic tiering and instant snapshots.',
    icon: Database,
  },
  {
    title: 'Advanced Analytics',
    description: 'Real-time dashboards, cohort analysis, and anomaly detection out of the box.',
    icon: BarChart3,
  },
  {
    title: 'Priority Support',
    description: 'Direct access to senior engineers with <60s median response in critical windows.',
    icon: Headphones,
  },
  {
    title: 'AI Auto Restructure',
    description: 'Automatic schema refactors and index proposals to keep performance razor-sharp.',
    icon: Sparkles,
  },
  {
    title: 'AI API Creation',
    description: 'Generate secure, typed REST and GraphQL endpoints from your data models.',
    icon: ServerCog,
  },
  {
    title: 'AI Schema Creations',
    description: 'Describe your entities in plain English—get normalized, versioned schemas instantly.',
    icon: Boxes,
  },
  {
    title: 'AI Data Pipelines',
    description: 'Declarative ETL with error recovery, retries, and lineage tracking.',
    icon: GitBranch,
  },
  {
    title: 'AI Tests',
    description: 'Autogenerated unit and integration tests for queries, mutations, and jobs.',
    icon: TestTube,
  },
];

export default function FeaturesPage() {
  return (
    <div className="relative min-h-screen w-full overflow-hidden text-white">
      

      {/* Hero */}
      <section className="relative z-10 container mx-auto px-6 pt-20 pb-10 md:pt-28">
        {/* halo ring behind title */}

        <div className="mx-auto max-w-3xl text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-indigo-400/20 bg-indigo-500/10 px-3 py-1 text-xs text-indigo-200">
            <Sparkles className="h-4 w-4" />
            Powered by AI • Built for scale
          </span>
          <h1 className="mt-4 bg-gradient-to-br from-white via-indigo-100 to-indigo-300 bg-clip-text text-5xl font-bold leading-tight text-transparent md:text-6xl">
            Everything you need to build <span className="text-indigo-300">faster</span>
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-indigo-200/80">
            A single platform for schema, APIs, pipelines, analytics, and automated testing—shipped with a clean,
            developer-first experience.
          </p>

          <div className="mt-8 flex items-center justify-center gap-3">
            <a
              href="/signup"
              className="group relative inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-indigo-600 px-6 py-3 text-sm font-semibold text-white shadow-[0_10px_30px_-10px_rgba(79,70,229,0.7)] transition-all hover:shadow-[0_20px_60px_-20px_rgba(79,70,229,0.9)] hover:scale-[1.02]"
            >
              Start free
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </a>
            <a
              href="/pricing"
              className="inline-flex items-center gap-2 rounded-xl border border-indigo-400/40 bg-white/0 px-6 py-3 text-sm font-semibold text-indigo-200 transition-colors hover:bg-indigo-500/10"
            >
              Pricing
            </a>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="relative z-10 container mx-auto px-6 pb-24">
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f, i) => (
            <FeatureCard key={f.title} feature={f} delay={i * 70} />
          ))}
        </div>

        {/* Compact status strip */}
        <div className="mx-auto mt-10 max-w-4xl rounded-2xl border border-indigo-400/20 bg-indigo-950/40 px-4 py-3 text-[13px] text-indigo-100/85 backdrop-blur">
          <div className="flex items-center justify-between">
            <span className="truncate">
              <b className="text-indigo-200">Status:</b> All systems operational • Region: us-central-1 • Queue depth:
              0.4%
            </span>
            <span className="hidden items-center gap-2 sm:flex">
              <span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,0.8)]" />
              Live
            </span>
          </div>
        </div>
      </section>
    </div>
  );
}